services:
  - type: web
    name: chat-app
    env: python
    plan: free
    branch: main
    buildCommand: |-
      pip install -r requirements.txt
    startCommand: |-
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0